name: Run Unit Tests

on:
  push:
    branches:
      - actions/pipeline
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup JDK 21 (Amazon Corretto)
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
    

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Unit Tests
      run: ./mvnw clean verify
