name: Build and Analysis

on:
  push:
    branches:
      - actions/pipeline
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  run-tests:
    uses: Studi-Grupo3/Back-End/.github/workflows/reusable-ci.yml@actions/pipeline
